name: "Install Sponge"
description: "Install the Sponge language"
author: "XDPXI"

branding:
  color: "yellow"
  icon: "arrow-down-circle"

inputs:
  version:
    description: "Sponge version to install"
    required: false
    default: "1.1.0"

runs:
  using: "composite"
  steps:
    - name: Install Sponge on Linux/macOS
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        URL="http://cdn.xdpxi.net:8716/sponge/$VERSION/sponge-$VERSION-$OS-x86_64.tar.gz"

        if command -v brew >/dev/null 2>&1; then
          echo "Installing via Homebrew..."
          brew tap XDPXI/tap
          brew install XDPXI/tap/sponge
        else
          echo "Homebrew not found, downloading directly..."
          curl -L "$URL" -o sponge.tar.gz
          tar -xzf sponge.tar.gz
          BINARY=$(find . -type f -name 'sponge*' -perm /111 | head -n1)
          chmod +x "$BINARY"
          sudo mv "$BINARY" /usr/local/bin/sponge
        fi

    - name: Install Sponge on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Write-Host "Installing Sponge via winget..."
        winget install --exact xdpxi.sponge --silent --accept-package-agreements --accept-source-agreements
