name: "Install Sponge."
description: "Install the Sponge language."
author: "XDPXI"

branding:
  color: "yellow"
  icon: "arrow-down-circle"

inputs:
  version:
    description: "Sponge version to install."
    required: false
    default: "1.1.0"

runs:
  using: "composite"
  steps:
    - name: Install SDL2 on Linux/macOS
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "Installing SDL2..."
        if command -v brew >/dev/null 2>&1; then
          brew install sdl2
        elif [[ "$(uname -s)" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
        fi

    - name: Install Sponge on Linux/macOS
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"

        if [[ "$(uname -s)" == "Darwin" ]]; then
          OS="macos"
        else
          OS="linux"
        fi

        URL="http://cdn.xdpxi.net:8716/sponge/$VERSION/sponge-$VERSION-$OS-x86_64.tar.gz"

        curl -L "$URL" -o sponge.tar.gz
        sudo tar -xzf sponge.tar.gz -C /usr/local/bin
        sudo chmod +x /usr/local/bin/Sponge
        sudo ln -sf /usr/local/bin/Sponge /usr/local/bin/sponge
        rm sponge.tar.gz

    - name: Install Sponge on Windows
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        Write-Host "Installing Sponge via winget..."
        winget install --exact xdpxi.sponge --silent --accept-package-agreements --accept-source-agreements

    - name: Test Sponge installation
      shell: bash
      run: |
        echo "Testing Sponge installation..."
        sponge -v
